services:
  api:
    build:
      context: "./api/"
      dockerfile: "./Dockerfile"
    ports:
      - "8787:8787"
    volumes:
      - "./api.dev.env:/app/.dev.vars"

  web:
    build:
      context: "./web/"
      dockerfile: "./Dockerfile"
    ports:
      - "3000:3000"
