services:
  api:
    build:
      context: "./api/"
      dockerfile: "./Dockerfile"
    tty: true
    ports:
      - "8787:8787"

  web:
    build:
      context: "./web/"
      dockerfile: "./Dockerfile"
    ports:
      - "3000:3000"
