// Generated by Wrangler by running `wrangler types`

interface Env {
  OAUTH_GOOGLE_CLIENT_ID: "456115587652-9o20ppfdr2fs6bgtcrg3d5g50j6o653c.apps.googleusercontent.com";
  OAUTH_GOOGLE_CLIENT_SECRET: "";
  OAUTH_GOOGLE_REDIRECT_URL: "http://localhost:3000/login/google";
  DB: D1Database;
  AI: Ai;
}
