name = "pathmaster-api"
main = "src/index.ts"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[vars]
OAUTH_GOOGLE_CLIENT_ID = ""
OAUTH_GOOGLE_CLIENT_SECRET = ""
OAUTH_GOOGLE_REDIRECT_URL = ""
