name = "pathmaster-api"
main = "src/index.ts"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[vars]
OAUTH_GOOGLE_CLIENT_ID = "456115587652-9o20ppfdr2fs6bgtcrg3d5g50j6o653c.apps.googleusercontent.com"
OAUTH_GOOGLE_CLIENT_SECRET = ""
OAUTH_GOOGLE_REDIRECT_URL = "http://localhost:3000/login/google"

[[d1_databases]]
binding = "DB"
database_name = "pathmaster-dev"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
