on:
  push:

name: "CI"

jobs:
  format:
    name: "Check code format"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Install prettier"
        run: |
          yarn global add prettier@3.3.3

      - name: "Check style with prettier"
        run: |
          prettier --check .

  binding:
    name: "Check worker bindings"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Install dependencies"
        run: |
          cd ./api/
          yarn install

      - name: "Generate binding code"
        run: |
          cd ./api/
          yarn cf-typegen
          yarn format

      - name: "Assert no changes"
        run: |
          if [ -n "$(git status --porcelain)" ]; then 
            echo "Binding code not up to date"
            exit 1
          fi

  build-api:
    name: "Build api"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Install dependencies"
        run: |
          cd ./api/
          yarn install

      - name: "Build project"
        run: |
          cd ./api/
          yarn build

  build-web:
    name: "Build web"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Install dependencies"
        run: |
          cd ./web/
          yarn install

      - name: "Build project"
        run: |
          cd ./web/
          yarn build

  docker-api:
    name: "Build Docker image for api"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Build Docker image"
        run: |
          docker build -f ./api/Dockerfile ./api/

  docker-web:
    name: "Build Docker image for web"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Build Docker image"
        run: |
          docker build -f ./web/Dockerfile ./web/
